EmployeeInfo/Controllers/EmployeeController.cs
using AutoMapper;
using EmployeeInfo.Repository.Data;
using EmployeeInfo.Repository.IRepository;
using EmployeeInfo.Service.IService;
using EmployeeInfo.Web.Factories;
using EmployeeInfo.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeInfo.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeeService _employeeService;
        private readonly IEmployeeFactory _employeeFactory;
        private readonly IProjectService _projectService;
        private readonly Linq2DbDataConnection _connection;
        private readonly IMapper _mapper;

        public EmployeeController(IEmployeeService employeeService, IEmployeeFactory employeeFactory, IProjectService projectService, Linq2DbDataConnection connection, IMapper mapper)
        {
            _employeeService = employeeService;
            _employeeFactory = employeeFactory;
            _projectService = projectService;
            _connection = connection;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadDataTable(int page = 1, int pageSize = 10)
        {
            var model = await _employeeFactory.GetEmployeesWithProjects(page, pageSize);
            return Json(model);
        }

        public async Task<IActionResult> Create()
        {
            var projects = _connection.Projects.ToList();
            //var projects = await _projectService.GetAllAsync();
            ViewBag.Projects = _mapper.Map<List<ProjectModel>>(projects);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(EmployeeModel model)
        {
            if (ModelState.IsValid)
            {
                await _employeeFactory.AddEmployeeAsync(model);
                TempData["success"] = "Employee added successfully!";
                return RedirectToAction("Index");
            }

            var projects = await _projectService.GetAllAsync();
            ViewBag.Projects = _mapper.Map<List<ProjectModel>>(projects);
            return View(model);
        }


        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
                return NotFound();

            var employee = await _employeeFactory.GetEmployeeByIdWithProjects(id);
            if (employee == null)
                return NotFound();

            //var projects = await _projectService.GetAllAsync();
            var projects = _connection.Projects.ToList();
            ViewBag.Projects = _mapper.Map<List<ProjectModel>>(projects);
            return View(employee);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EmployeeModel obj)
        {
            if (ModelState.IsValid)
            {
                await _employeeFactory.EditAsync(obj);
                TempData["success"] = "Employee Data edited successfully!";
                return RedirectToAction("Index");
            }

            var projects = await _projectService.GetAllAsync();
            ViewBag.Projects = _mapper.Map<List<ProjectModel>>(projects);
            return View(obj);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return NotFound();

            var result = await _employeeService.DeleteAsync(id);
            return Ok(result);
        }
    }
}

EmployeeInfo/Controllers/ProjectController.cs
using AutoMapper;
using EmployeeInfo.Entities.Domain;
using EmployeeInfo.Service.IService;
using EmployeeInfo.Web.Factories;
using EmployeeInfo.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace EmployeeInfo.Web.Controllers
{
    public class ProjectController : Controller
    {
        private readonly IProjectService _projectService;
        private readonly IProjectFactory _projectFactory;
        private readonly IEmployeeService _employeeService;
        private readonly IMapper _mapper;

        public ProjectController(IProjectService projectService, IProjectFactory projectFactory, IEmployeeService employeeService, IMapper mapper)
        {
            _projectService = projectService;
            _projectFactory = projectFactory;
            _employeeService = employeeService;
            _mapper = mapper;
        }

        public async Task<ActionResult> Index()
        {
            return View();
        }

        public async Task<IActionResult> LoadDataTable(int page = 1, int pageSize = 10)
        {
            var model = await _projectFactory.GetProjectsWithEmployees(page, pageSize);
            return Json(model);
        }

        public async Task<IActionResult> Create()
        {
            var employees = await _employeeService.GetAllAsync();
            ViewBag.Employees = _mapper.Map<List<EmployeeModel>>(employees);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(ProjectModel model)
        {
            if (ModelState.IsValid)
            {
                await _projectFactory.AddProjectAsync(model);
                TempData["success"] = "Project added successfully!";
                return RedirectToAction("Index");
            }

            return View(model);
        }


        public async Task<IActionResult> Edit(int id)
        {
            if (id == 0)
                return NotFound();

            var project = await _projectFactory.GetProjectByIdWithEmployees(id);
            if (project == null)
                return NotFound();

            var employees = await _employeeService.GetAllAsync();
            ViewBag.Employees = _mapper.Map<List<EmployeeModel>>(employees);
            return View(project);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(ProjectModel model)
        {
            if (ModelState.IsValid)
            {
                await _projectFactory.EditProjectAsync(model);
                TempData["success"] = "Project Data edited successfully!";
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            if (id == 0)
                return NotFound();

            var result = await _projectService.DeleteAsync(id);
            return Ok(result);
        }
    }
}

EmployeeInfo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EmployeeInfo</title>
    <link rel="stylesheet" href="~/css/bootswatchTheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EmployeeInfo.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Employee Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor02">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link " asp-controller="Project" asp-action="Index">Project</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

EmployeeInfo/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}